declare module 'react-router-dom';
declare module '@material-ui/core';
declare module 'react-helmet'
declare module 'animejs/lib/anime.es.js'
declare module 'segment-js'
declare module 'rellax'
declare module 'redux'
declare module 'react-redux'
declare module 'react-markdown'